variables:
- name: CodeQL.Enabled
  value: true

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      sourceAnalysisPool:
        name: 1ESPtTfsAgentBuildPoolSDL
    pool:
      name: 1ESPtTfsAgentBuildPool1
    customBuildTags:
    - ES365AIMigrationTooling

    stages:
    - stage: stage
      jobs:
      - job: Phase_1
        displayName: Agent job 1
        cancelTimeoutInMinutes: 1
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish Artifact: vsix'
            targetPath: '$(System.ArtifactsDirectory)'
            artifactName: vsix

        steps:
        - checkout: self
          clean: true
          fetchTags: false

        - task: UseNode@1
          displayName: Use Node
          inputs:
            version: '20.14.0'

        - task: NpmAuthenticate@0
          inputs:
            workingFile: .npmrc

        - task: Npm@1
          name: Npm_1
          displayName: npm install
          inputs:
            command: 'install'
            verbose: false

        - task: CmdLine@2
          displayName: Build
          inputs:
            script: node make.js build

        - task: CmdLine@2
          displayName: Run Tests
          inputs:
            script: node make.js test

        - task: CmdLine@2
          displayName: Create extension
          inputs:
            script: node make.js create

        - task: CopyFiles@2
          name: CopyFiles_5
          displayName: 'Copy Files to: $(System.ArtifactsDirectory)'
          inputs:
            Contents: '*.vsix'
            TargetFolder: $(System.ArtifactsDirectory)
