stages:
  - stage: BuildAndTest
    jobs:
      - job: BuildAndTestJob        
        displayName: Build and Test
        templateContext:
          outputs:
          - output: pipelineArtifact
            displayName: 'Publish Artifact: vsix'
            targetPath: '$(System.ArtifactsDirectory)'
            artifactName: vsix-unsigned
        steps:
        - checkout: self
          clean: true
          fetchTags: false

        - task: UseNode@1
          displayName: Use Node
          inputs:
            version: '20.19.4'

        - task: NpmAuthenticate@0
          inputs:
            workingFile: .npmrc

        - task: Npm@1
          name: Npm_1
          displayName: npm install
          inputs:
            command: 'install'
            verbose: false

        - task: CmdLine@2
          displayName: Build
          inputs:
            script: node make.js build

        - task: CmdLine@2
          displayName: Run Tests
          inputs:
            script: node make.js test

        - task: CmdLine@2
          displayName: Create extension
          inputs:
            script: node make.js create
        - task: CmdLine@2
          displayName: Create test extension
          inputs:
            script: node make.js createtest
        - task: CopyFiles@2
          name: CopyFiles_5
          displayName: 'Copy Files to: $(System.ArtifactsDirectory)'
          inputs:
            Contents: '*.vsix'
            TargetFolder: $(System.ArtifactsDirectory)  